# Generated by Django 3.2.18 on 2023-05-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_alter_filter_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('20000 to 30000', '20000 to 30000'), ('15000 to 20000', '15000 to 20000'), ('10000 to 15000', '10000 to 15000'), ('100 to 5000', '100 to 5000'), ('5000 to 10000', '5000 to 10000')], max_length=60),
        ),
    ]
